version: 2.1

orbs:
  maven: circleci/maven@1.0.1



workflows:

  build_and_test_SDK:
    jobs:
      - maven-build-and-test

  
  deploy:
    when:
      and: # All must be true to trigger
        - equal: [ release, <<pipeline.git.branch >> ]
    jobs:
      - deploy-to-maven-central


jobs:
  maven-build-and-test:
    executor:
      name: maven/default
      tag: '11.0'
    steps:
      - checkout
      - maven/with_cache:
          maven_command: mvn compile
          steps:
            - run: mvn compile
            - run: mvn verify
      - maven/process_test_results:
          test_results_path: client/target/surefire-reports


  deploy-to-maven-central:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          command: |
            pwd
            java --version
            mvn --version
            echo deployed



# 1. build & (unit)test the SDK
# 2. build & (unit)test EHRbase w/ SDK (as local dependency)
#    NOTE: make sure EHRbase is build w/ latest commit to SDK
# 3. run integation tests
#    - setup test environment
#    - execute robot tests
# 4. deploy (to maven central?)