version: 2.1

orbs:
  maven: circleci/maven@1.0.1



workflows:

  build_and_test:
    jobs:
      - maven-orb-test
  
  deploy:
    jobs:
      - deploy-to-maven-central


jobs:
  maven-orb-test:
    executor:
      name: maven/default
      tag: '11.0'
    steps:
      - checkout
      - maven/with_cache:
          maven_command: mvn compile
          steps:
            - run: mvn compile
      - maven/process_test_results:
          test_results_path: client/target/surefire-reports

  deploy-to-maven-central:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          command: |
            pwd
            java --version
            echo deployed



# 1. checkout code
# 2. build & (unit)test
# 3. run integation tests
#    - checkout ehrbase repo
#    - setup test environment
#    - execute robot tests
# 4. deploy (to maven central?)