version: 2.1

orbs:
  maven: circleci/maven@1.0.1



workflows:

  build_and_test_SDK:
    jobs:
      - maven-build-and-test
      - maven build-and-test-ehrbase:
          requires:
            - maven-build-and-test
  
  deploy:
    when:
      and: # All must be true to trigger
        - equal: [ release, <<pipeline.git.branch >> ]
    jobs:
      - deploy-to-maven-central


jobs:
  maven-build-and-test:
    description: |
      This job relies on the official circleci maven Orb!
      Documentation for this Orb is here: https://circleci.com/orbs/registry/orb/circleci/maven?version=1.0.1
      NOTE: make sure to read correct version of docs :)
    executor:
      name: maven/default
      tag: '11.0'
    steps:
      - checkout
      - maven/with_cache:
          maven_command: mvn compile
          steps:
            - run: mvn compile
            - run: mvn verify
            - run: mvn install -DskipTests
      - maven/process_test_results:
          test_results_path: client/target/surefire-reports
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .m2


  maven build-and-test-ehrbase:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run: java -version
      - attach_workspace:
          at: /home/circleci
      - run:
          command: |
            pwd
            ls -la


  deploy-to-maven-central:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          command: |
            pwd
            java --version
            mvn --version
            echo deployed



# 1. build & (unit)test the SDK
# 2. build & (unit)test EHRbase w/ SDK (as local dependency)
#    NOTE: make sure EHRbase is build w/ latest commit to SDK
# 3. run integation tests
#    - setup test environment
#    - execute robot tests
# 4. deploy (to maven central?)