version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  openjdk-install: cloudesire/openjdk-install@1.2.3

workflows:
  build_and_test:
    jobs:
      - maven-orb-test:
          maven_command: 'mvn clean install'
          test_result_path: client/target/surefire-reports
      

# 1. checkout code
# 2. build & (unit)test
# 3. run integation tests
#    - checkout ehrbase repo
#    - setup test environment
#    - execute robot tests
# 4. deploy (to maven central?)
